### ISSUE TITLE
Class 'lyquidity\xmldsig\xml\SignatureProductionPlaceV2' not found

### ISSUE THREAD

**Issue by sangar82** [bseddon/xml-signer#3]
Helllo!

After install the package with composer, I tried to sign an xml with the example provided in the user guide.

I obtain this error:
`Class 'lyquidity\xmldsig\xml\SignatureProductionPlaceV2' not found`

Perhaps something wrong with the namespace or something similar to #1 ? . I can't know what is happening. The namespace and the filename seem ok.

There are severals classes with the same problem (`SignerRoleV2` too) but `InputResourceInfo` is loading well.

I'm using the code with the last commit on main branch.

Thanks!

**Comment by adriamt** [comment]
Same for example for the class `AttributeNames`

**Comment by bseddon** [comment]
I've just downloaded the latest version and setup a test script which includes the example from the readme and it works OK for me.   Because so many classes are failing maybe the issue is something else.  For example, did you add 'use' statements for the classes referenced by the example?  Without these PHP will not be able to locate the class.  This is an omission by me so I have updated the example to show the necessary use statements which are:

```php
use lyquidity\xmldsig\CertificateResourceInfo;
use lyquidity\xmldsig\InputResourceInfo;
use lyquidity\xmldsig\KeyResourceInfo;
use lyquidity\xmldsig\ResourceInfo;
use lyquidity\xmldsig\XAdES;
use lyquidity\xmldsig\xml\SignatureProductionPlaceV2;
use lyquidity\xmldsig\xml\SignerRoleV2;
use lyquidity\xmldsig\XMLSecurityDSig;
```

If you have downloaded the source from GitHub (rather than installing using composer) then you will also need to add a reference to the xml-signer autoloader.php or PHP will be unable to find the classes even if the 'use' statements exist.  When xml-signer is installed using composer this step is not needed as its autoload.php is called when the composer autoload.php is referenced.

If you have downloaded the source from GitHub you will also need to separately download the dependent [requester](https://github.com/bseddon/requester) project.  You will then need to reference the autoload.php from this project.  Without these steps, PHP will be unable to find the certificate handling code.

download and the

**Comment by sangar82** [comment]
thanks for your reply @bseddon !

and sorry for the omited information:
- I'm using composer with the main branch
- I'm using ubuntu as SO (in a Virtual Machine launched with vagrant and virtualbox)
- When I copied the code, I added the use statements correctly (PhpStorm links the classes properly by the namespaces)

I think is something about your autoload functions, something about differences Windows-linux system, as a route, a path, or something else. The file name and namespace seems to be correct for psr-4.

**Comment by bseddon** [comment]
Wow, you're right.  It seems I did not push the change to the autoloader.  The change suggested in #1 has been pushed and a new new release is available for composer.  Thanks for letting me know.

**Comment by sangar82** [comment]
It works! Thank you!
